// === AUTOGENERATED START ===
/**
 * @param {number[]} this_t_today
 * @param {number[]} this_intensity_today
 * @param {number[]} this_load_today
 * @param {number[]} this_t_yesterday
 * @param {number[]} this_intensity_yesterday
 * @param {number[]} this_load_yesterday
 * @param {number[]} sun_intensity_ts
 * @param {number[]} sun_intensity_intensity
 * @param {number[]} sun_intensity_load
 * @returns {{t_today: number[], intensity_today: number[], load_today: number[], t_yesterday: number[], intensity_yesterday: number[], load_yesterday: number[]}}
 */
function update_sun_plot(this_t_today, this_intensity_today, this_load_today, this_t_yesterday, this_intensity_yesterday, this_load_yesterday, sun_intensity_ts, sun_intensity_intensity, sun_intensity_load) {
// === AUTOGENERATED END ===
  let t_today = [], intensity_today = [], load_today = [];
  let t_yesterday = [], intensity_yesterday = [], load_yesterday = [];
  let tmp_t = [], tmp_intensity = [], tmp_load = [];
  let last_day = null;

  for (let i = 0; i < sun_intensity_ts.length; i++) {
    let ts = sun_intensity_ts[i];
    let d = new Date(ts * 1000);
    let day = Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate());
    let clipped_ts = ts - day / 1000;
    if (last_day !== null && day !== last_day) {
      t_yesterday = tmp_t;
      intensity_yesterday = tmp_intensity;
      load_yesterday = tmp_load;
      tmp_t = [];
      tmp_intensity = [];
      tmp_load = [];
    }
    tmp_t.push(clipped_ts);
    tmp_intensity.push(sun_intensity_intensity[i]);
    tmp_load.push(sun_intensity_load[i]);
    last_day = day;
  }
  t_today = tmp_t;
  intensity_today = tmp_intensity;
  load_today = tmp_load;

  while (t_today.length < t_yesterday.length) { t_today.push(NaN); intensity_today.push(NaN); load_today.push(NaN); }
  while (t_yesterday.length < t_today.length) { t_yesterday.push(NaN); intensity_yesterday.push(NaN); load_yesterday.push(NaN); }

  return {
    t_today: t_today,
    intensity_today: intensity_today,
    load_today: load_today,
    t_yesterday: t_yesterday,
    intensity_yesterday: intensity_yesterday,
    load_yesterday: load_yesterday
  };
}
