// === AUTOGENERATED START ===
/**
 * @param {number[]} this_ts
 * @param {number[]} this_intensity
 * @param {number[]} this_zenith
 * @param {number[]} this_load
 * @param {number[]} time_series_ts
 * @param {number} geo_config_latitude
 * @param {number} load_config_solar_panel_area
 * @returns {{ts: number[], intensity: number[], zenith: number[], load: number[]}}
 */
function update_sun_intensity(this_ts, this_intensity, this_zenith, this_load, time_series_ts, geo_config_latitude, load_config_solar_panel_area) {
// === AUTOGENERATED END ===
  let startIdx = this_ts.indexOf(time_series_ts[0]);
  if (startIdx === -1) {
    this_ts = [];
    this_intensity = [];
    this_zenith = [];
    this_load = []; // NEW: zero initialize
  } else {
    this_ts = this_ts.slice(startIdx);
    this_intensity = this_intensity.slice(startIdx);
    this_zenith = this_zenith.slice(startIdx);;
    this_load = this_load.slice(startIdx); // NEW: slice
  }


  const n = time_series_ts.length;
  const S_zero = 1361; // solar constant at top of atmosphere

  for (let i = this_intensity.length; i < n; ++i) {
    let dt = new Date((time_series_ts[i]) * 1000); // plus half a year
    let startOfYear = Date.UTC(dt.getUTCFullYear(), 0, 0);
    let dayOfYear = (dt.getTime() - startOfYear) / 86400000;
    let E_zero = (1 + Math.cos(2 * Math.PI * dayOfYear / 365) * 0.035);  // perihelion in 1st of Jan, aphelion in 1st of July.
    let solar_declination = 23.44 * Math.sin(2 * Math.PI * (dayOfYear - 81) / 365) * Math.PI / 180;
    let solar_hour_angle = 15 * (dt.getUTCHours() + dt.getUTCMinutes() / 60 - 12) * Math.PI / 180;
    let latitude_rad = geo_config_latitude * Math.PI / 180;
    let zenith = Math.sin(latitude_rad) * Math.sin(solar_declination) + Math.cos(latitude_rad) * Math.cos(solar_declination) * Math.cos(solar_hour_angle);
    let solar_radiation = Math.max(S_zero * E_zero * zenith, 0);
    this_ts.push(time_series_ts[i]);
    this_intensity.push(solar_radiation);
    this_zenith.push(zenith);
    this_load.push(solar_radiation * load_config_solar_panel_area); // NEW: push load
  }
  return {'ts': this_ts, 'intensity': this_intensity, "zenith": this_zenith, 'load': this_load}
}
