// === AUTOGENERATED START ===
/**
 * @param {number[]} this_ts
 * @param {number} time_config_start_ts
 * @param {number} time_config_dt
 * @param {number} time_config_max_ts
 * @returns {{this_ts: number[]}}
 */
function update_time_series(this_ts, time_config_start_ts, time_config_dt, time_config_max_ts) {
// === AUTOGENERATED END ===
    var last_val = this_ts.length > 0 ? this_ts[this_ts.length - 1] : time_config_start_ts;
    this_ts.push(last_val + time_config_dt);
    while (this_ts.length > time_config_max_ts) {
        this_ts.shift();
    }
    return {"this_ts": this_ts}
}
