function weibullInvCDF(p, A, k) {
  return A * Math.pow(-Math.log(1 - p), 1 / k);
}
// === AUTOGENERATED START ===
/**
 * @param {number[]} this_edges
 * @param {number} wind_config_A
 * @param {number} wind_config_k
 * @param {number} wind_config_min_bin
 * @param {number} wind_config_max_bin
 * @param {number} wind_config_nr_bins
 * @returns {{edges: number[]}}
 */
function update_weibull_bins(this_edges, wind_config_A, wind_config_k, wind_config_min_bin, wind_config_max_bin, wind_config_nr_bins) {
// === AUTOGENERATED END ===
  // Recompute bin edges based on current wind_config parameters
  let nStates = wind_config_nr_bins;
  // Always use min_bin and max_bin (clip edges accordingly)
  let minBin = wind_config_min_bin;
  let maxBin = wind_config_max_bin;
  const maxP = 1 - Math.exp(-Math.pow(maxBin / wind_config_A, wind_config_k));

  let edges = [];
  for (let i = 0; i <= nStates; i++) {
    const p = (i / nStates) * maxP;
    let edge = weibullInvCDF(p, wind_config_A, wind_config_k);
    // Clamp to min/max bin limits
    if (edge < minBin) edge = minBin;
    if (edge > maxBin) edge = maxBin;
    edges.push(edge);
  }
  return {'edges': edges};
}
