function seededRandom(seed) {
  // Simple LCG: https://en.wikipedia.org/wiki/Linear_congruential_generator
  // Constants from Numerical Recipes
  let m = 4294967296, // 2^32
      a = 1664525,
      c = 1013904223;
  let state = seed % m;
  return function () {
    state = (a * state + c) % m;
    return state / m;
  }
}
// === AUTOGENERATED START ===
/**
 * @param {number[]} this_ts
 * @param {number[]} this_target_bin
 * @param {number[]} this_speed
 * @param {number[]} this_load
 * @param {number[]} weibull_bins_edges
 * @param {number[]} time_series_ts
 * @param {number} load_config_nr_5mw_tubrines
 * @param {number} wind_config_rated_ws
 * @returns {{ts: number[], target_bin: number[], speed: number[], load: number[]}}
 */
function update_wind_data(this_ts, this_target_bin, this_speed, this_load, weibull_bins_edges, time_series_ts, load_config_nr_5mw_tubrines, wind_config_rated_ws) {
// === AUTOGENERATED END ===
  // Shift arrays to align start
  let startIdx = this_ts.indexOf(time_series_ts[0]);
  if (startIdx === -1) {
    this_ts = [];
    this_target_bin = [];
    this_speed = [];
    this_load = [];
  } else {
    this_ts = this_ts.slice(startIdx);
    this_target_bin = this_target_bin.slice(startIdx);
    this_speed = this_speed.slice(startIdx);
    this_load = this_load.slice(startIdx);
  }

  const n = time_series_ts.length;

  for (let i = this_speed.length; i < n; ++i) {
    const ts_val = time_series_ts[i];
    const rand = seededRandom(ts_val);
    
    let dt = i === 0 ? 900 : time_series_ts[i] - time_series_ts[i-1];
    let f = 0.05;
    let z = Math.sqrt(-2.0 * Math.log(rand() + 1e-10)) * Math.cos(2 * Math.PI * rand());
    let delta_bins = Math.round(z * Math.sqrt(dt) * f);
    let new_target_bin = this_target_bin[this_target_bin.length - 1] + delta_bins;
    new_target_bin = Math.max(0, Math.min(new_target_bin, weibull_bins_edges.length - 2));

    this_target_bin.push(new_target_bin)

    let target_speed = 0.5 * (weibull_bins_edges[new_target_bin] + weibull_bins_edges[new_target_bin + 1]);
    // Spring-mass-damper: x = position, v = velocity (speed update); acceleration = -k*(x - target) - C*v
    // Names:
    //   this_speed: x (position); V: v (velocity); target_speed: target position
    let x = this_speed[this_speed.length - 1];
    let v = (this_speed.length > 1) ? ((this_speed[this_speed.length - 1] - this_speed[this_speed.length - 2])/dt) : 0;
    let dt_sec = dt; // dt in seconds

    // Tunable spring parameters
    let k = 0.1;    // spring constant, adjust for "pull" towards target (must be <1 for stability at dt=900)
    let C = 0.015;    // damping, critical damping at C^2 = 4km
    let m = 1;        // mass (can leave 1)

    // Compute acceleration
    let a = (-k * (x - target_speed) - C * v) / m;

    // Euler step
    v = v + a;
    x = x + v;


    this_ts.push(time_series_ts[i]);
    this_speed.push(Math.max(x, 0));
    // Power is proportional to v^3 below rated, flat above rated_ws; P = Pmax * (v/rated_ws)^3 for v <= rated_ws
    let ws = this_speed[this_speed.length - 1];
    let n = load_config_nr_5mw_tubrines;
    let rated = wind_config_rated_ws;
    let max_p = 5_000_000; // 5MW per turbine
    let p = ws <= rated ? max_p * Math.pow(ws / rated, 3) : max_p;
    this_load.push(n * p);
  }

  return {"ts": this_ts, "target_bin": this_target_bin, "speed": this_speed, "load": this_load};
}
