// === AUTOGENERATED START ===
/**
 * @param {number} this_wind_distance
 * @param {number} this_watermark
 * @param {number[]} wind_data_speed
 * @param {number[]} wind_data_ts
 * @returns {{wind_distance: number, watermark: number}}
 */
function update_wind_distance(this_wind_distance, this_watermark, wind_data_speed, wind_data_ts) {
// === AUTOGENERATED END ===
  let idx = wind_data_ts.indexOf(this_watermark);
  if (idx === -1) idx = 0;
  let new_distance = this_wind_distance;
  for (let i = idx + 1; i < wind_data_ts.length; i++) {
    let dt = wind_data_ts[i] - wind_data_ts[i - 1];
    new_distance += wind_data_speed[i] * dt / 3600;
  }
  let new_watermark = wind_data_ts.length > 0 ? wind_data_ts[wind_data_ts.length - 1] : this_watermark;
  return {'wind_distance': new_distance, 'watermark': new_watermark};
}
