// === AUTOGENERATED START ===
/**
 * @param {number[]} this_t_today
 * @param {number[]} this_speed_today
 * @param {number[]} this_load_today
 * @param {number[]} this_t_yesterday
 * @param {number[]} this_speed_yesterday
 * @param {number[]} this_load_yesterday
 * @param {number[]} wind_data_ts
 * @param {number[]} wind_data_speed
 * @param {number[]} wind_data_load
 * @returns {{t_today: number[], speed_today: number[], load_today: number[], t_yesterday: number[], speed_yesterday: number[], load_yesterday: number[]}}
 */
function update_wind_plot(this_t_today, this_speed_today, this_load_today, this_t_yesterday, this_speed_yesterday, this_load_yesterday, wind_data_ts, wind_data_speed, wind_data_load) {
// === AUTOGENERATED END ===
  let t_today = [], speed_today = [], load_today = [];
  let t_yesterday = [], speed_yesterday = [], load_yesterday = [];
  let tmp_t = [], tmp_speed = [], tmp_load = [];
  let last_day = null;

  for (let i = 0; i < wind_data_ts.length; i++) {
    let ts = wind_data_ts[i];
    let d = new Date(ts * 1000);
    let day = Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate());
    let clipped_ts = ts - day / 1000;
    if (last_day !== null && day !== last_day) {
      t_yesterday = tmp_t;
      speed_yesterday = tmp_speed;
      load_yesterday = tmp_load;
      tmp_t = [];
      tmp_speed = [];
      tmp_load = [];
    }
    tmp_t.push(clipped_ts);
    tmp_speed.push(wind_data_speed[i]);
    tmp_load.push(wind_data_load[i]);
    last_day = day;
  }
  t_today = tmp_t;
  speed_today = tmp_speed;
  load_today = tmp_load;

  while (t_today.length < t_yesterday.length) { t_today.push(NaN); speed_today.push(NaN); load_today.push(NaN); }
  while (t_yesterday.length < t_today.length) { t_yesterday.push(NaN); speed_yesterday.push(NaN); load_yesterday.push(NaN); }

  return {
    t_today: t_today,
    speed_today: speed_today,
    load_today: load_today,
    t_yesterday: t_yesterday,
    speed_yesterday: speed_yesterday,
    load_yesterday: load_yesterday
  };
}
