function seededRandom(seed) {
  // Simple LCG: https://en.wikipedia.org/wiki/Linear_congruential_generator
  // Constants from Numerical Recipes
  let m = 4294967296, // 2^32
      a = 1664525,
      c = 1013904223;
  let state = seed % m;
  return function () {
    state = (a * state + c) % m;
    return state / m;
  }
}
// === AUTOGENERATED START ===
/**
 * @param {number[]} this_ts
 * @param {number[]} this_speed
 * @param {number[]} this_z
 * @param {number} wind_config_mean
 * @param {number} wind_config_phi
 * @param {number} wind_config_sigma
 * @param {number} wind_config_seasonal_period
 * @param {number[]} time_series_ts
 * @returns {{ts: number[], speed: number[], z: number[]}}
 */
function update_wind_data(this_ts, this_speed, this_z, wind_config_mean, wind_config_phi, wind_config_sigma, wind_config_seasonal_period, time_series_ts) {
// === AUTOGENERATED END ===
  // Shift arrays to align start
  let startIdx = this_ts.indexOf(time_series_ts[0]);
  if (startIdx === -1) {
    this_ts = [];
    this_speed = [];
    this_z = [];
  } else {
    this_ts = this_ts.slice(startIdx);
    this_speed = this_speed.slice(startIdx);
    this_z = this_z.slice(startIdx);
  }

  // Based on the Python fake_wind process, but with z persistence (this_z).
  const phi = wind_config_phi, sigma = wind_config_sigma, mean = wind_config_mean;
  const n = time_series_ts.length;
  var z;

  for (let i = this_speed.length; i < n; ++i) {
    // AR(1): this_z[t] = phi * this_z[t-1] + sqrt(1-phi^2) * noise[t]
    const ts_val = time_series_ts[i];
    const rand = seededRandom(ts_val);
    const eps = Math.sqrt(-2 * Math.log(rand())) * Math.cos(2 * Math.PI * rand());
    if (i === 0) {
      z = Math.sqrt(1 - phi * phi) * eps;
    } else {
      z = phi * this_z[this_z.length - 1] + Math.sqrt(1 - phi * phi) * eps;
    }
    // Compute the slow term directly
    const slow_arg = (6 * Math.PI * ts_val) / wind_config_seasonal_period;
    const slow = - 0.3 * Math.cos(slow_arg);
    const x = Math.exp(Math.log(mean) + slow + sigma * z) - 0.5;
    this_ts.push(time_series_ts[i]);
    this_speed.push(Math.max(x, 0));
    this_z.push(z);
  }
  // Keep arrays aligned and no longer than n
  if (this_ts.length > n) {
    let excess = this_ts.length - n;
    this_ts = this_ts.slice(excess);
    this_speed = this_speed.slice(excess);
    this_z = this_z.slice(excess);
  }

  return {"ts": this_ts, "speed": this_speed, "z": this_z};
}
