from collections import defaultdict
from enum import Enum, auto
from inspect import get_annotations
import os
import re
from typing import Any, Literal, get_args, get_origin
from bokeh.document import Document
from bokeh.embed import components
from bokeh.events import DocumentReady
from bokeh.models import ColumnDataSource, CustomJS
from bokeh.models.dom import DOMElement
import pydantic


JsType = Literal["number", "string", "boolean", "object", "array", "date", "bigint", "symbol", "function", "undefined", "null", "map", "set"]  # fmt: skip
_JS_TYPES: frozenset[str] = frozenset(get_args(JsType))


class InputType(Enum):
    SingleValue = auto()
    Array = auto()


class SuperCDSColumn(pydantic.BaseModel):
    name: str
    js_type: JsType
    initial_value: list = []
    input_type: InputType = InputType.Array


class LinkedSuperCDSColumn(pydantic.BaseModel):
    super_cds_column: SuperCDSColumn
    super_cds_name: str

    @property
    def js_attr_name(self) -> str:
        return f"{self.super_cds_name}_{self.super_cds_column.name}"

    @property
    def js_attr_type(self) -> str:
        if self.super_cds_column.input_type == InputType.SingleValue:
            return self.super_cds_column.js_type
        else:
            return f"{self.super_cds_column.js_type}[]"

    @property
    def js_input(self) -> str:
        if self.super_cds_column.input_type == InputType.SingleValue:
            return f"{self.super_cds_name}.data.{self.super_cds_column.name}[0]"
        else:
            return f"[... {self.super_cds_name}.data.{self.super_cds_column.name}]"


class SuperCDS:
    def __init__(
        self,
        name: str,
        columns: list[SuperCDSColumn],
        depends_on_columns: list[LinkedSuperCDSColumn] = [],
    ):
        self.name = name
        if columns:
            if len({col.input_type for col in columns}) > 1:
                raise ValueError(f"Different input types found for {self.name}. {self.columns!r}")
        self._base_columns = columns
        self.source = ColumnDataSource({column.name: column.initial_value for column in columns})
        self.depends_on_columns = depends_on_columns

    @property
    def columns(self) -> dict[str, LinkedSuperCDSColumn]:
        if not hasattr(self, "_base_columns"):
            return {}
        return {base_column.name: LinkedSuperCDSColumn(super_cds_column=base_column, super_cds_name=self.name) for base_column in self._base_columns}

    @property
    def dependencies(self) -> set[str]:
        return {depends_on_column.super_cds_name for depends_on_column in self.depends_on_columns}

    @property
    def callback_name(self) -> str:
        return f"update_{self.name}"

    def callback_location(self, file_dir: str) -> str:
        return os.path.join(file_dir, f"{self.name}.js")

    def _update_signature(self, file_dir: str) -> None:
        START_MARKER = "// === AUTOGENERATED START ==="
        END_MARKER = "// === AUTOGENERATED END ==="

        if len(self.dependencies) == 0:
            return

        js_path = self.callback_location(file_dir)
        if not os.path.exists(js_path):
            with open(js_path, "w") as f:
                f.write(f"{START_MARKER}\n")
                f.write(f"{END_MARKER}\n")
                f.write(f"  console.log('Running function {self.callback_name}');\n")
                f.write(f"""  return {{{", ".join(f"'{col}': this_{col}" for col in self.columns)}}}\n""")
                f.write("}\n")

        with open(js_path, "r+") as f:
            contents = f.read()
            if START_MARKER not in contents or END_MARKER not in contents:
                raise ValueError(f"File '{js_path}' is missing start or end marker")

            start_idx = contents.index(START_MARKER) + len(START_MARKER)
            end_idx = contents.index(END_MARKER)

            jsdoc_lines = [f" * @param {{{col.js_attr_type}}} this_{col.super_cds_column.name}" for col in self.columns.values()]
            jsdoc_lines += [f" * @param {{{linked_col.js_attr_type}}} {linked_col.js_attr_name}" for linked_col in self.depends_on_columns]

            params = [f"this_{col.name}" for col in self._base_columns] + [linked_col.js_attr_name for linked_col in self.depends_on_columns]

            if self._base_columns:
                returns_contents = ", ".join(f"{col.super_cds_column.name}: {col.js_attr_type}" for col in self.columns.values())
                returns_line = f" * @returns {{{{{returns_contents}}}}}"
            else:
                returns_line = " * @returns {{}}"
            jsdoc_text = "/**\n"
            if jsdoc_lines:
                jsdoc_text += "\n".join(jsdoc_lines) + "\n"
            jsdoc_text += returns_line + "\n"
            jsdoc_text += " */\n"
            func_signature = f"function {self.callback_name}({', '.join(params)}) {{\n"

            between_markers = jsdoc_text + func_signature

            # Re-compose file contents
            new_contents = contents[:start_idx] + "\n" + between_markers + contents[end_idx:]

            # Write back to file
            f.seek(0)
            f.write(new_contents)
            f.truncate()


class SuperCDSDataflow:
    def __init__(self, super_cdss: list[SuperCDS], js_dir: str, tick_ms: int, engine_setup: str, engine_code: str):
        if not (isinstance(js_dir, str) and os.path.isdir(js_dir)):
            raise ValueError(f"js_dir '{js_dir}' is not a valid directory")
        self.js_dir = js_dir
        self.super_cdss = {super_cds.name: super_cds for super_cds in super_cdss}
        self.doc = Document()
        self.engine_code = engine_code
        self.engine_setup = engine_setup
        self.tick_ms = tick_ms

    def update_signatures(self):
        for super_cds in self.super_cdss.values():
            super_cds._update_signature(self.js_dir)

    def clear_js_files(self):
        response = input(f"Are you sure? This will delete all .js files in {self.js_dir}. Only by entering 'y' will this actually happen.").lower()
        if response != "y":
            return
        for filename in os.listdir(self.js_dir):
            if filename.endswith(".js"):
                file_path = os.path.join(self.js_dir, filename)
                if os.path.isfile(file_path):
                    os.remove(file_path)

    def get_components_and_script(self, dom_elements: dict[str, DOMElement] = {}) -> tuple[str, dict[str, str]]:
        # Fresh document each embed so DocumentReady handlers do not stack, and so
        # roots + js_on_event stay on the same instance that components() serializes.
        self.doc = Document()
        self._attach_loop(self.doc)

        # Bokeh's components() uses OutputDocumentFor: it only keeps document-level
        # state (e.g. js_on_event) if the passed models are *exactly* this doc's roots.
        new_dom_elements = dict(dom_elements)
        for value in dom_elements.values():
            self.doc.add_root(value)
        for i, super_cds in enumerate(self.super_cdss.values()):
            new_dom_elements[f"source_{i}"] = super_cds.source
            self.doc.add_root(super_cds.source)

        assert set(new_dom_elements.values()) == set(self.doc.roots)

        script, divs = components(new_dom_elements)
        return script, divs

    def _attach_loop(self, doc):
        self.update_signatures()
        callbacks = "\n"
        for super_cds in self.super_cdss.values():
            if len(super_cds.dependencies) > 0:
                with open(super_cds.callback_location(self.js_dir), "r") as f:
                    cb = f.read()
                callbacks += cb + "\n"

        dirty_requests = defaultdict(list)
        for super_cds in self.super_cdss.values():
            for dependency in super_cds.dependencies:
                dirty_requests[dependency].append(super_cds.name)

        unresolved_cdss = sorted(self.super_cdss.keys())
        resolved_cdss = set()
        graph = []
        while len(unresolved_cdss) > 0:
            for unresolved_cds_name in unresolved_cdss:
                unresolved_cds = self.super_cdss[unresolved_cds_name]
                if len(unresolved_cds.dependencies - resolved_cdss) == 0:
                    graph.append(unresolved_cds_name)
                    resolved_cdss.add(unresolved_cds_name)
                    unresolved_cdss.remove(unresolved_cds_name)
                    break
            else:
                raise ValueError(f"Couldn't establish non-circular dependency graph. Resolved_cdss: {resolved_cdss}. Graph so far: {graph}")

        update_script = ""
        for cds_name in graph:
            # Should be different logic if dependecies is empty
            # jsdoc_lines = [f" * @param {{{col.js_attr_type}}} this_{col.super_cds_column.name}" for col in self.columns.values()]
            # jsdoc_lines += [f" * @param {{{linked_col.js_attr_type}}} {linked_col.js_attr_name}" for linked_col in self.depends_on_columns]

            super_cds = self.super_cdss[cds_name]
            reflog_checks = [
                f'refLog["{super_cds.name}"]["{col.super_cds_column.name}"] != {super_cds.name}.data.{col.super_cds_column.name}'
                for col in super_cds.columns.values()
            ]
            update_script += f"""
                // check if need for update
                if (!dirty.includes("{super_cds.name}")) {{
                    if ({" || ".join(reflog_checks)}) {{
                        dirty.push("{super_cds.name}");
                    }}
                }}
                if (dirty.includes("{super_cds.name}")) {{"""
            if len(super_cds.dependencies) > 0:
                args = [col.js_input for col in list(super_cds.columns.values()) + super_cds.depends_on_columns]
                input_type = next(iter(super_cds.columns.values())).super_cds_column.input_type
                if input_type == InputType.SingleValue:
                    assignments = [f"'{col.super_cds_column.name}': [new_data.{col.super_cds_column.name}]" for col in super_cds.columns.values()]
                else:
                    assignments = [f"'{col.super_cds_column.name}': new_data.{col.super_cds_column.name}" for col in super_cds.columns.values()]

                update_script += f"""
                    new_data = {super_cds.callback_name}({", ".join(args)});
                    {super_cds.name}.data = {{
                        {", ".join(assignments)}
                    }};"""
            if len(dirty_requests[super_cds.name]) > 0:
                update_script += f"""
                    ["{'","'.join(dirty_requests[super_cds.name])}"].forEach((dep) => {{if (!dirty.includes(dep) && dep !== "") {{dirty.push(dep)}}}});"""
            update_script += f"""
                    dirty.splice(dirty.indexOf('{super_cds.name}'), 1);"""

            update_script += f"""
                    {"; ".join(it.replace("!=", "=") for it in reflog_checks)};

                }}
            """

        c = CustomJS(
            args={super_cds.name: super_cds.source for super_cds in self.super_cdss.values()},
            code=f"""
                {callbacks}

                var refLog = {{{",".join(f"'{graph_it}': {{}}" for graph_it in graph)}}};
                var dirty = [];
                var new_data;
                {self.engine_setup}

                function run_update_script() {{
                    {self.engine_code}
                    {update_script}
                }};
                setInterval(run_update_script, {self.tick_ms});
            """,
        )
        doc.js_on_event(DocumentReady, c)


def _normalize_js_type_annotation(js_type_ann: Any) -> str:
    if isinstance(js_type_ann, str) and js_type_ann in _JS_TYPES:
        return js_type_ann
    if get_origin(js_type_ann) is Literal:
        args = get_args(js_type_ann)
        if len(args) == 1 and args[0] in _JS_TYPES:
            return args[0]
    raise TypeError(f"Column annotation must be a JsType string or Literal[JsType], got {js_type_ann!r}")


class AnnotatedStr(str):
    """String that behaves like a normal ``str`` (e.g. for Bokeh field names) but can carry metadata."""

    # This lets static analyzers know about these attributes.
    linked_column: LinkedSuperCDSColumn
    extra_info: Any

    def __new__(cls, value: str, linked_column: LinkedSuperCDSColumn, extra_info: Any = None, /, **meta: Any):
        obj = str.__new__(cls, value)
        obj.extra_info = extra_info
        for k, v in meta.items():
            setattr(obj, k, v)
        obj.linked_column = linked_column
        return obj


class SuperCDSMeta(type):
    """Builds a :class:`SuperCDS` from annotated class attributes and wires column names as :class:`AnnotatedStr`."""

    def __new__(mcs, cls_name: str, bases: tuple[type, ...], namespace: dict[str, Any]) -> type:
        cls = super().__new__(mcs, cls_name, bases, namespace)
        if cls_name.startswith("_") or getattr(cls, "__abstract_cds__", False):
            return cls

        annotations = get_annotations(cls)
        input_type = namespace.get("input_type", InputType.Array)
        depends_spec = namespace.get("depends_on_columns", [])

        super_columns: list[SuperCDSColumn] = []
        column_names: list[str] = []
        for col_name, js_type_ann in annotations.items():
            if col_name not in namespace:
                continue
            init_val = namespace[col_name]
            if not isinstance(init_val, list):
                continue
            js_type = _normalize_js_type_annotation(js_type_ann)
            super_columns.append(
                SuperCDSColumn(
                    name=col_name,
                    js_type=js_type,
                    initial_value=init_val,
                    input_type=input_type,
                )
            )
            column_names.append(col_name)

        if not super_columns:
            return cls

        cds_name = namespace.get("__cds_name__", re.sub(r"(?<!^)(?=[A-Z])", "_", cls_name).lower())
        linked_deps: list[LinkedSuperCDSColumn] = []
        items: tuple[Any, ...] = depends_spec if isinstance(depends_spec, (list, tuple)) else (depends_spec,)
        for item in items:
            if isinstance(item, type) and getattr(item, "super_cds", None) is not None:
                linked_deps.extend(item.super_cds.columns.values())
            elif isinstance(item, AnnotatedStr):
                linked_deps.append(item.linked_column)
            else:
                raise TypeError(f"depends_on_columns entry must be a SuperCDS class or column ref, got {item!r}")
        super_cds = SuperCDS(cds_name, super_columns, depends_on_columns=linked_deps)

        for col_name in column_names:
            base_col = next(c for c in super_columns if c.name == col_name)
            linked = LinkedSuperCDSColumn(super_cds_column=base_col, super_cds_name=cds_name)
            setattr(
                cls,
                col_name,
                AnnotatedStr(
                    col_name,
                    linked,
                    extra_info={"js_type": base_col.js_type, "super_cds_name": cds_name},
                    js_type=base_col.js_type,
                    super_cds_name=cds_name,
                ),
            )

        cls.super_cds = super_cds
        cls.source = super_cds.source
        return cls
