from enum import Enum, auto
import os
from typing import Literal
from bokeh.models import ColumnDataSource, CustomJS
import pydantic


JsType = Literal["number", "string", "boolean", "object", "array", "date", "bigint", "symbol", "function", "undefined", "null", "map", "set"]  # fmt: skip


class InputType(Enum):
    SingleValue = auto()
    Array = auto()


class SuperCDSColumn(pydantic.BaseModel):
    name: str
    js_type: JsType
    initial_value: list = []
    input_type: InputType = InputType.Array


class LinkedSuperCDSColumn(pydantic.BaseModel):
    super_cds_column: SuperCDSColumn
    super_cds_name: str

    @property
    def js_attr_name(self) -> str:
        return f"{self.super_cds_name}_{self.super_cds_column.name}"

    @property
    def js_attr_type(self) -> str:
        if self.super_cds_column.input_type == InputType.SingleValue:
            return self.super_cds_column.js_type
        else:
            return f"{self.super_cds_column.js_type}[]"


class SuperCDS:
    def __init__(
        self,
        name: str,
        columns: list[SuperCDSColumn],
        depends_on_columns: list[LinkedSuperCDSColumn] = [],
    ):
        self.name = name
        if columns:
            if len({col.input_type for col in columns}) > 1:
                raise ValueError(f"Different input types found for {self.name}. {self.columns!r}")
        self._base_columns = columns
        self.source = ColumnDataSource({column.name: column.initial_value for column in columns})
        self.depends_on_columns = depends_on_columns

    @property
    def columns(self) -> dict[str, LinkedSuperCDSColumn]:
        if not hasattr(self, "_base_columns"):
            return {}
        return {base_column.name: LinkedSuperCDSColumn(super_cds_column=base_column, super_cds_name=self.name) for base_column in self._base_columns}

    @property
    def dependencies(self) -> set[str]:
        return {depends_on_column.super_cds_name for depends_on_column in self.depends_on_columns}

    @property
    def callback_name(self) -> str:
        return f"update_{self.name}"

    def callback_location(self, file_dir: str) -> str:
        return os.path.join(file_dir, f"{self.name}.js")

    def _update_signature(self, file_dir: str) -> None:
        START_MARKER = "// === AUTOGENERATED START ==="
        END_MARKER = "// === AUTOGENERATED END ==="

        if len(self.dependencies) == 0:
            return

        js_path = self.callback_location(file_dir)
        if not os.path.exists(js_path):
            with open(js_path, "w") as f:
                f.write(f"{START_MARKER}\n")
                f.write(f"{END_MARKER}\n")
                f.write(f"  console.log('Running function {self.callback_name})")
                f.write("}\n")

        with open(js_path, "r+") as f:
            contents = f.read()
            if START_MARKER not in contents or END_MARKER not in contents:
                raise ValueError(f"File '{js_path}' is missing start or end marker")

            start_idx = contents.index(START_MARKER) + len(START_MARKER)
            end_idx = contents.index(END_MARKER)

            jsdoc_lines = [f" * @param {{{col.js_attr_type}}} this_{col.super_cds_column.name}" for col in self.columns.values()]
            jsdoc_lines += [f" * @param {{{linked_col.js_attr_type}}} {linked_col.js_attr_name}" for linked_col in self.depends_on_columns]

            params = [f"this_{col.name}" for col in self._base_columns] + [linked_col.js_attr_name for linked_col in self.depends_on_columns]

            if self._base_columns:
                returns_contents = ", ".join(f"this_{col.super_cds_column.name}: {col.js_attr_type}" for col in self.columns.values())
                returns_line = f" * @returns {{{{{returns_contents}}}}}"
            else:
                returns_line = " * @returns {{}}"
            jsdoc_text = "/**\n"
            if jsdoc_lines:
                jsdoc_text += "\n".join(jsdoc_lines) + "\n"
            jsdoc_text += returns_line + "\n"
            jsdoc_text += " */\n"
            func_signature = f"function {self.callback_name}({', '.join(params)}) {{\n"

            between_markers = jsdoc_text + func_signature

            # Re-compose file contents
            new_contents = contents[:start_idx] + "\n" + between_markers + contents[end_idx:]

            # Write back to file
            f.seek(0)
            f.write(new_contents)
            f.truncate()


class SuperCDSDataflow:
    def __init__(self, super_cdss: list[SuperCDS], js_dir: str):
        if not (isinstance(js_dir, str) and os.path.isdir(js_dir)):
            raise ValueError(f"js_dir '{js_dir}' is not a valid directory")
        self.js_dir = js_dir
        self.super_cdss = {super_cds.name: super_cds for super_cds in super_cdss}

    def update_signatures(self):
        for super_cds in self.super_cdss.values():
            super_cds._update_signature(self.js_dir)

    def clear_js_files(self):
        response = input(f"Are you sure? This will delete all .js files in {self.js_dir}. Only by entering 'y' will this actually happen.").lower()
        if response != "y":
            return
        for filename in os.listdir(self.js_dir):
            if filename.endswith(".js"):
                file_path = os.path.join(self.js_dir, filename)
                if os.path.isfile(file_path):
                    os.remove(file_path)

    def propegate_loop(self) -> CustomJS:
        self.update_signatures()
        callbacks = ""
        for super_cds in self.super_cdss.values():
            if len(super_cds.dependencies) > 0:
                with open(super_cds.callback_location(self.js_dir), "r") as f:
                    cb = f.read()
                callbacks += cb + "\n"

        unresolved_cdss = sorted(self.super_cdss.keys())
        resolved_cdss = set()
        graph = []
        while len(unresolved_cdss) > 0:
            for unresolved_cds_name in unresolved_cdss:
                unresolved_cds = self.super_cdss[unresolved_cds_name]
                if len(unresolved_cds.dependencies - resolved_cdss) == 0:
                    graph.append(unresolved_cds_name)
                    resolved_cdss.add(unresolved_cds_name)
                    unresolved_cdss.remove(unresolved_cds_name)
                    break
            else:
                raise ValueError(f"Couldn't establish non-circular dependency graph. Resolved_cdss: {resolved_cdss}. Graph so far: {graph}")

        return CustomJS(
            args={super_cds.name: super_cds.source for super_cds in self.super_cdss.values()},
            code=f"""
                {callbacks}
            """,
        )
